on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: self-hosted

  strategy: 
    matrix:
      node-version: [12.x]

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Install NPM dependencies
      run: npm install
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/